sudo: false

language: php

notifications:
    email:
        on_success: never
        on_failure: change

branches:
    only:
        - master

php: 5.5

matrix:
    include:
        - php: 5.5
          env: CS_CHECK=true COVERAGE=true
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2

before_script: composer install

script:
    - |
        if [[ "$CS_CHECK" != "" ]]; then
            composer cs-check
        fi
    - composer test

after_success:
    - |
        if [[ "$COVERAGE" != "" ]]; then
            composer require codacy/coverage --dev
            composer coverage-clover
            php vendor/bin/codacycoverage clover coverage.xml
        fi
